function Scroller(t){this.options=t,this.button=null,this.stop=!1}Scroller.prototype.constructor=Scroller,Scroller.prototype.createButton=function(){this.button=document.createElement("button"),this.button.classList.add("scroll-button"),this.button.classList.add("scroll-button--hidden"),this.button.textContent="TOP",document.body.appendChild(this.button)},Scroller.prototype.init=function(){this.createButton(),this.checkPosition(),this.click(),this.stopListener()},Scroller.prototype.scroll=function(){return 0==this.options.animate||"false"==this.options.animate?void this.scrollNoAnimate():"normal"==this.options.animate?void this.scrollAnimate():"linear"==this.options.animate?void this.scrollAnimateLinear():void 0},Scroller.prototype.scrollNoAnimate=function(){document.body.scrollTop=0,document.documentElement.scrollTop=0},Scroller.prototype.scrollAnimate=function(){this.scrollTop()>0&&0==this.stop&&setTimeout(function(){this.scrollAnimate(),window.scrollBy(0,-Math.abs(this.scrollTop())/this.options.normal.steps)}.bind(this),this.options.normal.ms)},Scroller.prototype.scrollAnimateLinear=function(){this.scrollTop()>0&&0==this.stop&&setTimeout(function(){this.scrollAnimateLinear(),window.scrollBy(0,-Math.abs(this.options.linear.px))}.bind(this),this.options.linear.ms)},Scroller.prototype.click=function(){this.button.addEventListener("click",function(t){t.stopPropagation(),this.scroll()}.bind(this),!1),this.button.addEventListener("dblclick",function(t){t.stopPropagation(),this.scrollNoAnimate()}.bind(this),!1)},Scroller.prototype.hide=function(){this.button.classList.add("scroll-button--hidden")},Scroller.prototype.show=function(){this.button.classList.remove("scroll-button--hidden")},Scroller.prototype.checkPosition=function(){window.addEventListener("scroll",function(t){this.scrollTop()>this.options.showButtonAfter?this.show():this.hide()}.bind(this),!1)},Scroller.prototype.stopListener=function(){var t=this.scrollTop();window.addEventListener("scroll",function(o){this.scrollTop()>t&&this.stopTimeout(200),t=this.scrollTop()}.bind(this,t),!1),window.addEventListener("wheel",function(t){t.deltaY>0&&this.stopTimeout(200)}.bind(this),!1)},Scroller.prototype.stopTimeout=function(t){this.stop=!0,setTimeout(function(){this.stop=!1,console.log(this.stop)}.bind(this),t)},Scroller.prototype.scrollTop=function(){var t=document.documentElement.scrollTop||document.body.scrollTop;return t};var options={showButtonAfter:200,animate:"normal",normal:{steps:15,ms:1e3/60},linear:{px:80,ms:1e3/60}},scroll=new Scroller(options);scroll.init();
$(function(){if($("#titlesticky").length){var o=$("#titlesticky"),t=$("#titlesticky").offset().top,i=$("#titlesticky").height();$(window).scroll(function(){var s=$("#Blog1").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:44}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
$(function(){if($("#left-sticky").length){var o=$("#left-sticky"),t=$("#left-sticky").offset().top,i=$("#left-sticky").height();$(window).scroll(function(){var s=$("#Blog1").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:44}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
$(function(){if($("#sidebar-fokus").length){var o=$("#sidebar-fokus"),t=$("#sidebar-fokus").offset().top,i=$("#sidebar-fokus").height();$(window).scroll(function(){var s=$("#Blog1").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:44}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
$(function(){if($("#sidebar-item").length){var o=$("#sidebar-item"),t=$("#sidebar-item").offset().top,i=$("#sidebar-item").height();$(window).scroll(function(){var s=$(".inshare").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:44}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
function resizeThumb(el,from,to){$(el).each(function(){$(this).attr({'src':$(this).attr('src').replace('/s'+from+'-c/','/s'+to+'-c/'),'width':to,'height':to})})}
$(function(){resizeThumb('.related-thumb','72','180')})
$(document.body).append('<div id="page-loader"><div class="page-loader"><img src="https://1.bp.blogspot.com/-1WT9O4jm2Aw/XCZ3zUIHS4I/AAAAAAAACcw/yXWgsv-ORSsTT7njxQqi3yu0BVTd1ruMQCLcBGAs/s1600/stopwatch.gif" style="width: 200px;"/></div></div>');
$(window).on("beforeunload", function() {
$('#page-loader').fadeIn(100).delay(9000).fadeOut(100);});
$(function(){$('#controltab1').click(function(){var divID=$(this).attr('href');$('html,body').animate({scrollTop:$(divID).offset().top},{duration:'slow',easing:'swing'})})});$(function(){$('#controltab2').click(function(){var divID=$(this).attr('href');$('html,body').animate({scrollTop:$(divID).offset().top},{duration:'slow',easing:'swing'})})});
var uri=window.location.toString();if(uri.indexOf("%3D","%3D")>0){var clean_uri=uri.substring(0,uri.indexOf("%3D"));window.history.replaceState({},document.title,clean_uri)}
var uri=window.location.toString();if(uri.indexOf("%3D%3D","%3D%3D")>0){var clean_uri=uri.substring(0,uri.indexOf("%3D%3D"));window.history.replaceState({},document.title,clean_uri)}
var uri=window.location.toString();if(uri.indexOf("&m=1","&m=1")>0){var clean_uri=uri.substring(0,uri.indexOf("&m=1"));window.history.replaceState({},document.title,clean_uri)}
var uri=window.location.toString();if(uri.indexOf("?m=1","?m=1")>0){var clean_uri=uri.substring(0,uri.indexOf("?m=1"));window.history.replaceState({},document.title,clean_uri)}
function replaceText(){if(!document.getElementById){return}
bodyText=document.getElementById("Blog1");theText=bodyText.innerHTML;theText=theText.replace(/default/gi,"mqdefault");bodyText.innerHTML=theText}replaceText()
jQuery(document).ready(function($){ $(".multitab-widget-content-widget-id").hide(); $("ul.multitab-widget-content-tabs-id li:first a").addClass("multitab-widget-current").show(); $(".multitab-widget-content-widget-id:first").show(); $("ul.multitab-widget-content-tabs-id li a").click(function() { $("ul.multitab-widget-content-tabs-id li a").removeClass("multitab-widget-current a"); $(this).addClass("multitab-widget-current"); $(".multitab-widget-content-widget-id").hide(); var activeTab = $(this).attr("href"); $(activeTab).fadeIn(); return false; }); });
